### PR TITLE
Fix GiSysFactors up/down + Add systematics in new strategy (Fpix + mass reconstruction)

### PR DESCRIPTION
**Pull request by DenkMybu**
Fix the erros introduced by PR of 15th of september 
- GiSysFactors up and down were back to gaussian randomisation instead of 2% flat

Adding the Fpix + mass reconstruction plots for all systematics

### CODE REVIEW

**Comment by tvami** [comment]
hi @DenkMybu thanks for the PR! I'm wondering if we should break it up to two, since you are adding the new strategy too. I think we'll need to branch out the code that's used for AN-22-129 and then the master can go on with the new stuff

(maybe it's also time to ask for a new AN for the next version of the paper)

**Comment by DenkMybu** [comment]
Hey @tvami , sure thing. I can change the PR and only put the corrections on the systematics, or do you want to make the new branch first and then we merge everything ?

**Comment by tvami** [comment]
hi @DenkMybu let's push the correction in this PR, then I'll branch out for AN-22-129 and after that you can update master with all the new stuff

**Comment by DenkMybu** [comment]
Alright, I had implemented the new stuff with Fpix before fixing the systematics error so I'll work around that a make a new PR !

**Pull request closed without merging**
